name: CI
on:
  push:
    branches:
      - v3
  pull_request:
    branches:
      - v3

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          yarn install

      - name: Check types
        run: |
          yarn build
